all: loay output_program simple_program

loay: loay.c
	gcc loay.c -o loay

output_program: loay1.c loay2.c
	gcc loay1.c loay2.c -o output_program

simple_program: simple_program.c
	gcc simple_program.c -o simple_program

clean:
	rm -f process_creation output_program simple_program
